### ISSUE TITLE
Command line parameter 1: 'TCPServeraddress 10.14.25.13 is not valid

### ISSUE THREAD

**Issue by armogit** [jeremymcgee73/PSTSM#1]
When i try to run this command:
_Invoke-TsmCommand  -TCPServerAddress 10.14.25.13 -TCPPort 1503 -Command run TEST_SCRIPT_

it fails with this error:
**Command line parameter 1: 'TCPServeraddress 10.14.25.13' is not valid.
At C:\Users\user\Documents\WindowsPowerShell\Modules\PSTSM\Public\Invoke-TSMcommand.ps1:95 char:13
          Throw $errorOut
            ~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Command line pa... is not valid.:String) [], RuntimeExc  
  eption
    + FullyQualifiedErrorId : Command line parameter 1: 'TCPServeraddress 10.14.25.13' is not valid.´**


i have tried everything from:
_Invoke-TsmCommand  -TCPServerAddress '10.14.25.13' -TCPPort 1503 -Command run TEST_SCRIPT
Invoke-TsmCommand  -TCPServerAddress "10.14.25.13" -TCPPort 1503 -Command run TEST_SCRIPT
Invoke-TsmCommand  -TCPServerAddress 10.14.25.13 -TCPPort 1503 -Command run "TEST_SCRIPT"_
Still same error..

Hope there is help out there :)

**Comment by jeremymcgee73** [comment]
Have you tried the following? The run command is a TSM command, so that should be part of the command string.

`Invoke-TsmCommand -TCPServerAddress 10.14.25.13 -TCPPort 1503 -Command "run TEST_SCRIPT"`

**Comment by armogit** [comment]
Yeah, i have tried that also.
The only workaround i found is to change the opt. File with the new server
information with PowerShell and change it back again and run the command
with invoke-tsmcommand "run test"

**Comment by armogit** [comment]
You have any ideas on waht the problem is?

**Comment by jeremymcgee73** [comment]
I resolved the issue. I was not generating the parameter that is passed to TSM correctly. You should be good to go now. I have updated the module here and in the gallery.

**Comment by armogit** [comment]
It still isn't working mate.

how is the correct syntax? :)

**Comment by jeremymcgee73** [comment]
Did you uninstall the old version and install the new? The test command I posted above works.

**Comment by armogit** [comment]
Yes, now it gives me this error:
**Command line parameter 2: 'TCPPort 1503' is not valid.**

**Comment by jeremymcgee73** [comment]
Whoops. Try it now. It was missing an equal sign in the TSM parameter.
